packages:
  - ./
  - docs
  - playground
  - playground-vue
catalog:
  '@iconify-json/lucide': ^1.2.30
  '@iconify-json/simple-icons': ^1.2.28
  '@iconify/vue': ^4.3.0
  '@internationalized/date': ^3.7.0
  '@internationalized/number': ^3.6.0
  '@nuxt/fonts': ^0.11.0
  '@nuxt/icon': ^1.11.0
  '@nuxt/kit': ^3.16.0
  '@nuxt/module-builder': ^0.8.4
  '@nuxt/schema': ^3.16.0
  '@nuxt/test-utils': ^3.17.2
  '@nuxtjs/color-mode': ^3.5.2
  '@release-it/conventional-changelog': ^10.0.0
  '@standard-schema/spec': ^1.0.0
  '@tanstack/vue-table': ^8.21.2
  '@unhead/vue': ^1.11.20
  '@unocss/nuxt': ^66.1.0-beta.7
  '@vinicunca/akar': ^1.2.2
  '@vinicunca/eslint-config': ^3.10.0
  '@vinicunca/perkakas': ^1.5.0
  '@vinicunca/pohon': latest
  '@vinicunca/unocss-preset': ^1.12.0
  '@vitejs/plugin-vue': ^5.2.2
  '@vue/test-utils': ^2.4.6
  '@vueuse/core': ^13.0.0
  '@vueuse/integrations': ^13.0.0
  colortranslator: ^4.1.0
  consola: ^3.4.0
  defu: ^6.1.4
  embla-carousel: ^8.5.2
  embla-carousel-auto-height: ^8.5.2
  embla-carousel-auto-scroll: ^8.5.2
  embla-carousel-autoplay: ^8.5.2
  embla-carousel-class-names: ^8.5.2
  embla-carousel-fade: ^8.5.2
  embla-carousel-vue: ^8.5.2
  embla-carousel-wheel-gestures: ^8.0.1
  eslint: ^9.22.0
  fuse.js: ^7.1.0
  happy-dom: ^17.4.4
  joi: ^17.13.3
  knitwork: ^1.2.0
  magic-string: ^0.30.17
  mlly: ^1.7.4
  nuxt: ^3.16.0
  nuxt-component-meta: ^0.10.0
  ohash: ^2.0.11
  pathe: ^2.0.3
  release-it: ^18.1.2
  superstruct: ^2.0.2
  tinyglobby: ^0.2.12
  typescript: ^5.8.2
  unocss: ^66.1.0-beta.7
  unocss-variants: 1.0.0-alpha.2
  unplugin: ^2.2.0
  unplugin-auto-import: ^19.1.1
  unplugin-vue-components: ^28.4.1
  valibot: ^0.42.1
  vaul-vue: ^0.4.1
  vite: ^6.2.2
  vite-plugin-inspect: ^11.0.0
  vitest: ^3.0.8
  vitest-environment-nuxt: ^1.0.1
  vue: ^3.5.13
  vue-router: ^4.5.0
  vue-tsc: ^2.2.8
  yup: ^1.6.1
  zod: ^3.24.2
ignoredBuiltDependencies:
  - '@parcel/watcher'
  - esbuild
  - vue-demi
  - workerd
onlyBuiltDependencies:
  - better-sqlite3
