catalog:
  '@iconify/vue': ^4.3.0
  '@internationalized/date': ^3.7.0
  '@internationalized/number': ^3.6.0
  '@nuxt/fonts': ^0.10.3
  '@nuxt/icon': ^1.10.3
  '@nuxt/kit': ^3.15.4
  '@nuxt/module-builder': ^0.8.4
  '@nuxt/schema': ^3.15.4
  '@nuxt/test-utils': ^3.15.4
  '@nuxtjs/color-mode': ^3.5.2
  '@release-it/conventional-changelog': ^10.0.0
  '@standard-schema/spec': ^1.0.0
  '@tanstack/vue-table': ^8.21.2
  '@unhead/vue': ^1.11.18
  '@vinicunca/akar': 1.0.0
  '@vinicunca/eslint-config': ^3.4.0
  '@vinicunca/perkakas': ^1.2.3
  '@vinicunca/unocss-preset': ^1.7.0
  '@vue/test-utils': ^2.4.6
  '@vueuse/core': ^12.5.0
  '@vueuse/integrations': ^12.5.0
  colortranslator: ^4.1.0
  consola: ^3.4.0
  defu: ^6.1.4
  embla-carousel: ^8.5.2
  embla-carousel-auto-height: ^8.5.2
  embla-carousel-auto-scroll: ^8.5.2
  embla-carousel-autoplay: ^8.5.2
  embla-carousel-class-names: ^8.5.2
  embla-carousel-fade: ^8.5.2
  embla-carousel-vue: ^8.5.2
  embla-carousel-wheel-gestures: ^8.0.1
  eslint: ^9.20.1
  fuse.js: ^7.1.0
  happy-dom: ^17.1.1
  joi: ^17.13.3
  knitwork: ^1.2.0
  magic-string: ^0.30.17
  mlly: ^1.7.4
  nuxt: ^3.15.4
  nuxt-component-meta: ^0.10.0
  ohash: ^1.1.4
  pathe: ^2.0.3
  release-it: ^18.1.2
  superstruct: ^2.0.2
  tinyglobby: ^0.2.11
  unplugin: ^2.2.0
  unplugin-auto-import: ^19.1.1
  unplugin-vue-components: ^28.4.1
  valibot: ^0.42.1
  vaul-vue: ^0.3.0
  vitest: ^3.0.7
  vitest-environment-nuxt: ^1.0.1
  vue-tsc: ^2.2.0
  yup: ^1.6.1
  zod: ^3.24.2
packages:
  - ./
  - docs
  - playground
  - playground-vue
